server:
  port: 8012
spring: 
  cloud:
    config: 
      server:
        git:
          uri: https://github.com/gongyuansong/Spring.git/
          search-paths: spring_cloud_configCenter
          username: gongyuansong
          password: 替换密码
  application:
    name: configServer
eureka:
  client:
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8002/eureka/