server:
  port: 8003
spring: 
  application:
    name: eurekaserver03
eureka:
  client:
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8001/eureka/,http://localhost:8002/eureka/