server:
  port: 8003
spring: 
  application:
    name: eurekaserver
eureka:
  instance:
    hostname: eureka3
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1:8001/eureka/,http://eureka2:8002/eureka/