server:
  port: 8001
spring: 
  application:
    name: eurekaserver
eureka:
  instance:
    hostname: eureka1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka2:8002/eureka/,http://eureka3:8003/eureka/