server:
  port: 8010
spring: 
  application:
    name: feign
eureka:
  client:
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
      defaultZone: http://eureka1:8001/eureka/
feign:
  hystrix:
    enabled: true